Repository sofyanox12/blackmarket-website, pull requests merged in 2022-09, with the labels that each got.

#11 Change Name in products.html
  products.html
Labels: enhancement

#12 Add formbox
  .DS_Store
  assets/collagepicture2.jpg
  main.html
  styles/main.css
Labels: update, enhancement, good

#16 merubah navbar biar keren dan menambah footer
  main.html
  styles/main.css
Labels: update, enhancement
